name: eyeshalfclosed
description: Blog of Emaad Ahmed Manzoor
url: "http://eyeshalfclosed.com"

# Author info
author_name: Emaad Ahmed Manzoor
author_image_path: /images/author-image.jpeg
author_bio: |
    Engineer at Yahoo! · Interned
    at Tachyon Technologies · CS undergrad
    from BITS Pilani Goa
github_url: "https://github.com/emaadmanzoor"
twitter_url: "https://twitter.com/emaadmanzoor"
linkedin_url: "https://linkedin.com/in/emaadmanzoor"
feed_url: "http://feeds.feedburner.com/eyeshalfclosed"
email: "emaadmanzoor@gmail.com"

# Markdown rendering
markdown: kramdown
kramdown:
  smart_quotes: apos,apos,quot,quot

# Site settings
permalink: pretty
relative_permalinks: false
pygments: true
