name: eyeshalfclosed

# Author info
author_name: Emaad Ahmed Manzoor
author_image_path: /images/author-image.jpeg
author_bio: |
    Masters student at KAUST.
    Formerly engineer at Yahoo!, intern at Tachyon Technologies,
    undergrad at BITS-Pilani Goa Campus.    
github_url: "https://github.com/emaadmanzoor"
twitter_url: "https://twitter.com/emaadmanzoor"
linkedin_url: "https://linkedin.com/in/emaadmanzoor"
feed_url: "http://feeds.feedburner.com/eyeshalfclosed"
email: "emaadmanzoor@gmail.com"

# Markdown rendering
markdown: kramdown
kramdown:
  smart_quotes: apos,apos,quot,quot

# Site settings
permalink: pretty
relative_permalinks: false
pygments: true

# prose.io settings
prose:
  siteurl: "http://eyeshalfclosed.com"
  media: "/images"
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          value: "New Title"
      - name: "tags"
        field:
          element: "text"
          value: "tags"
