name: Alex Wapniarski
description: Blog of Alex Wapniarski
url: "http://www.alex-w.com"

# Author info
author_name: Alex Wapniarski
author_image_path: /images/author-image.jpeg

# External services
github_url: "https://github.com/alex-wap"
linkedin_url: "https://linkedin.com/in/wapniarski"
email: "wapniarski@gmail.com"

# Markdown rendering
kramdown:
  #  smart_quotes: apos,apos,quot,quot
  parse_block_html: true

# Site settings
permalink: /blog/:year/:month/:day/:title/

# important since the site is compiled
# on Github's servers
timezone: America/San_Francisco

# important since the site is compiled
include: [_redirects]
